### ISSUE TITLE
Duplicate of hapi-engine.ts

### ISSUE THREAD

**Issue by firehist** [Boulangerie/angular2-universal-hapiour#2]
Wondering why two `hapi-engine.ts`?
https://github.com/Boulangerie/angular2-universal-hapiour/blob/master/src/hapi-engine.ts
https://github.com/Boulangerie/angular2-universal-hapiour/blob/master/src/app/hapi-engine.ts

**Comment by yannickglt** [comment]
It was a bad move I guess 😃
Thanks for report!
